openapi: 3.1.0
info:
  title: virtual-card
  version: '1.0'
  summary: Portal Backend REST API for virtual-card module
servers:
  - url: 'http://localhost:3000'
paths:
  /api/portal/virtualCard/v1/info:
    parameters: []
    get:
      summary: ''
      operationId: get-api-portal-virtualCard-v1-info
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    $ref: ./mobile.yaml#/components/schemas/ResponseStatus
                  code:
                    type: string
                  data:
                    oneOf:
                      - $ref: '#/components/schemas/VirtualCardInfoResponse'
                      - type: 'null'
                        properties: {}
components:
  schemas:
    VirtualCardInfoResponse:
      title: VirtualCardInfoResponse
      type: object
      description: ''
      examples:
        - id: 142
          firstName: Alice
          lastName: Smith
          email: alice.smith@gmail.com
          dateOfBirth: '1997-10-31'
          emailVerified: true
          signUpDate: '2019-08-24'
      properties:
        cardNumber:
          type: string
          description: Unique identifier for the given user.
        created:
          type: string
        certificates:
          type: array
          items:
            $ref: '#/components/schemas/Certificate'
      required:
        - cardNumber
        - created
    Certificate:
      title: Certificate
      type: object
      properties:
        serialNumber:
          type: string
        autoExtend:
          type: boolean
        validity:
          type: string
        purpose:
          type: string
        publisher:
          type: string
        receiver:
          type: string
        state:
          type: string
        alternativeName:
          type: string
        print:
          type: string
        purposes:
          type: array
          items:
            type: string
